### ISSUE TITLE
Volume setters seem to have no effect

### ISSUE THREAD

**Issue by on3iro** [beefchimi/earwurm#20]
Hi,

thanks for this cool library. I just tried it out and it seems to work really well.
However I noticed that no matter which volume setter I use they seem to have no effect.
I tried setting the volume on the manager, the stack and the sound itself, but to no avail.
The loop setter on the sound for the other hand seems to work fine, so I am fairly confident, that I use the API correctly.

Do you have any idea, what I could be doing wrong?

Thanks in advance :)

Here's the code I am using inside a react `useEffect`-hook:

```ts
if (!soundManager.unlocked) return
const soundStack = soundManager.get(soundKey)
if (!soundStack) return

soundStack.volume = soundMap[soundKey].volume

soundStack.volume = 0.1
const sound = soundStack.prepare()
sound.then((s) => {
   s.play()
})
```

And here's my manager initialization:
```ts
const BASE_VOLUME = 0.5 // hardcoded for now
const soundMap: Record<GameSoundKeys, SoundFile> = {
  drawCard: {
    volume: 0.5,
    soundFile: drawCard,
  },
  // ...some more sound definitions
} as const

export default soundMap

export const soundManager = new Earwurm()
soundManager.volume = BASE_VOLUME

const stacks = Object.entries(soundMap).map(([id, sound]) => ({
  id,
  path: sound.soundFile,
}))

soundManager.add(...stacks)
```

**Comment by beefchimi** [comment]
Hey @on3iro 👋 

Thanks for flagging this! Your code looks good... not sure why this isn't working 🤔  I will try my best to look into this over the weekend if I have time 🙏

**Comment by on3iro** [comment]
> Hey @on3iro 👋
> 
> Thanks for flagging this! Your code looks good... not sure why this isn't working 🤔 I will try my best to look into this over the weekend if I have time 🙏

Thanks a lot :) - apart from the volume issue  the library is working perfectly for me, though! :+1:

**Comment by beefchimi** [comment]
**Update:** I've got this working - it was a silly mistake with how I connect the gain/audio nodes. You can see a working prototype here:

https://codesandbox.io/s/earwurm-volume-test-m95wei?file=/src/audio.ts

I will try to open a PR and cut a new release tomorrow. I'll ping you once a new version is out.

**Comment by on3iro** [comment]
Awesome, thanks for fixing this so quickly 🤩

**Comment by beefchimi** [comment]
**Issue now resolved in:** https://github.com/beefchimi/earwurm/pull/22

**New release:** https://github.com/beefchimi/earwurm/releases/tag/v0.2.0

**React demo:** https://codesandbox.io/s/earwurm-volume-test-m95wei

**Vanilla JS demo:** https://codepen.io/beefchimi/pen/vYzXmGx/e1c925ead3f8a2740d4cb144fe68ab99
